### ISSUE TITLE
Init colorama

### ISSUE THREAD

**Issue by ak545** [gildasio/h2t#4]
Hi!
Before using colorama it is necessary to call initialization.
Necessary to make minor changes to the file output.py

Before:
```
import json
from colorama import Fore, Style

def help():
```

After:

```
import json
from colorama import init
from colorama import Fore, Style

# Init colorama
init()

def help():

```

**Comment by gildasio** [comment]
Good observation, @ak545 , thanks! I'll send it in next push.

Thank you!
